language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: QItcWnesyEqc4mUd7ECG4eOCVUe69buPsmnCQVqdztNYS3ocx7ETFM0h2eZaWHum6hkk0PcgIHF53iuKCx39gsqW/GALnxSl4X7irFnHKolul2305cbNcWFtlcIwq7OmUNxhgaxuUfaKK3ZtEeEYsRLih2ZQklq3ykqyu8d87EGs/VDZqLsG9xBkHDZpCpNumxvFojTZQqJEgPFYSMnOYWayYx6yXJhjh4cL4Gbkk0uZ7LzY025Scs196IbJ1WOlYGShCV52hpDEq1eR4kyUub1jU8/UvZTcB7EwfoPIm/tkw0oIR56jhM0Ly+TXOHoNF5HxP0mJs1BIvXQF7oU2YAtf2SgZqaj/fzs6iIyH+F1twELPQ7Ypq/laKz6J3Xn9xrvnsNm2RcbMsxf2yCoJ+7sj0f/DPs6BiegGA7uFXR99xNzTgM3sIbbe9I9Ja0V9muZMr2mMy+6o9XqeXoJGAkR1LzfujbyzZNKn57sMs5CNsYhWbmhS8BjfL0t+KFq/creY/XRG0CJXt8hN098Md1H2rzEfcBYpIJ1WwvTAcJwpatYapor9RBP0M904DjmRj21oQlK+WOqzZEnOnGXFdewPjxUHEcLbSLDp5aqp0M2HtAAJPxw63zWegwFm+yq3lpskY4CVpXkJ2Iii9q3a5H4reNncWvzrAaDA1iKoNG8=
  app: app-blackjack
before_install:
- chmod +x mvnw
