language: java
jdk:
- openjdk8
deploy:
  provider: heroku
  api_key:
    secure: dBIKsIRM26oJrs8znoUvu7E8Q1ovCI1+baK0oCi3BJf2Vrt4lRS+kPALjr0ybieOO/1hH1sIr5+YSSaEWqpV/XF1sRs8bQgBQflpkhEfuY4WuazTYkg9Y4LDTJcDI5QFt4Imf3jgfjB+wbJn+xYDGvztR7OrTOS2JUqrMsv+7+queSKIha2A76LZzgLRpOQLvxLFrOGU2iQ3eZy8dhJWuoah3MFPAfb+fvSWZMncen0gnV6h1EzgtD4LHKJQzLmB4x9v7MkfVKEzxlbjOA01LHhVL/iEOEJpsi0yAFdTGmmCoE9IFOLq9rE4h+r6tjNh2mhVABznd/re+DLKQbc0sFqip23FlRi1znEonCfoM/75gc0NgjtL2Vn5Flb2ToFSfTHHIjscOjYpKUjPWK9+thW8cDPsRhJ+LjKsgqvOi2SZBd1p59j6n03+oW9p6bibpBXpjtCoUniGe2dCfOVwmjn3xr8m6sRw5gytcC1aNlzIYWlZ3W0Ji26dxwC5L9qhmShFWHt/whfLMoUCS62cxozup8WnAEnC+IqmL+wDFTsAzlpslge7bJAA3S98rA7e3JT2FrX1G5+peaKFr24DEj3tPx01JAhKVi65AaObhpw9gB24/w8lDwqQaJ6OeRsSZYdURgfk6aO5/pPhoZ8ziLoA2U1ka02I0Tcvr2/2gM4=
  app: app-blackjack
before_install:
- chmod +x mvnw